jobs:
  build-job:
    docker:
      - image: circleci/php:7.1.13-apache-node-browsers
    working_directory: /tmp/my-project
    steps:
      - checkout
      - run: echo "A first hello"
      - run: php index.php
            
  deploy-job:
    docker:
      - image: circleci/php:7.1.13-apache-node-browsers
    working_directory: /tmp/my-project  
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "06:a9:53:05:16:b5:c3:28:dc:aa:8b:07:3f:3b:6f:16"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:iamtryingtobuildci.git HEAD:refs/heads/master
            heroku run python manage.py deploy
            heroku restart

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master